name: CI/CD Pipeline

on:
  workflow_dispatch: # manual start
  push:
    branches-ignore:
      - 'benchmarks'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  # --- JOB 1: BENCHMARK (Native) ---
  benchmark:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # needed for changed-files tool
      
      # zig cache
      - name: Setup Cache
        uses: ./.github/actions/setup-zig-cache

      # Calculate Version
      - name: Calculate Version
        id: version
        run: |
          # Default to 0.0.1 if file missing
          if [ -f VERSION ]; then
            MAN_VERSION=$(cat VERSION | tr -d '[:space:]')
          else
            MAN_VERSION="0.0.1"
          fi
          FULL_VERSION="${MAN_VERSION}-build.${{ github.run_number }}"
          echo "bench_version=$FULL_VERSION" >> $GITHUB_ENV

      # checks for changes in the Dockerfile
      # a push containing dockerfile changes triggers docker-publish.yml. As the two workflows run asynchronously we need to make sure that the benchmark step builds a new image from the Dockerfile instead of pulling from the container registry to avoid an outdated image.
      - name: Check for Dockerfile Steps
        id: changed-dockerfile
        uses: tj-actions/changed-files@v44
        with:
          files: Dockerfile

      - name: Pull Image
        if: steps.changed-dockerfile.outputs.any_changed == 'false'
        run: |
          if docker pull ghcr.io/timo-eberl/tracy-bench:latest; then
            docker tag ghcr.io/timo-eberl/tracy-bench:latest rmse-bench
          else
            echo "Pull failed, building locally..."
            docker build -t rmse-bench --target benchmark-env .
          fi

      - name: Dockerfile Changed -> Build new Benchmark Image
        uses: docker/build-push-action@v5
        if: steps.changed-dockerfile.outputs.any_changed == 'true'
        with:
          context: .
          target: benchmark-env
          push: false
          tags: rmse-bench
          cache-from: type=gha # use docker layer caching
          cache-to: type=gha,mode=max

      
      # render the target image
      - name: Render Scene
        run: |
          docker run --rm \
          -v $(pwd):/app \
          -v ~/.cache/zig:/root/.cache/zig \
          -w /app \
          rmse-bench zig build run-zig -Doptimize=ReleaseSafe

      # add the rendered image to the artifacts
      - name: Upload Render Preview
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: render-preview-${{ env.bench_version }}
          # TODO change to exr
          path: render_zig.tga
          retention-days: 7


      # Run Test & Capture Output
      # set volumes so that we don't have to rebuild upon code change
      - name: Run RMSE Benchmark
        run: |
          # RAW_SCORE=$(docker run --rm rmse-bench zig build rmse_run)
          RAW_SCORE=$(docker run --rm \
          -v $(pwd):/app \
          -v ~/.cache/zig:/root/.cache/zig \
          -w /app \
          rmse-bench zig build rmse_run --summary none -Doptimize=Debug)
          python3 scripts/create_log.py "$RAW_SCORE" rmse_results.txt
          
          cat rmse_results.txt

      # 4. Save Report
      - name: Upload Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: rmse-report-${{ env.bench_version }}
          path: rmse_results.txt

      # Move data to orphan branch
      - name: Checkout Data Branch
        uses: actions/checkout@v4
        with:
          ref: benchmarks
          path: data-branch
          fetch-depth: 0
      #  run script to integrate new data
      - name: Run Python Script
        run: |
          python3 scripts/update_benchmark.py rmse_results.txt data-branch/history.csv
          
          # Debug: check content
          cat data-branch/history.csv

          # ensure directory exists
          mkdir -p data-branch/logs
          mv rmse_results.txt data-branch/logs/${{ env.bench_version }}.txt
      
      # 3. Generate Dashboard (README.md)
      - name: Generate Dashboard
        run: |
          # Inputs:
          # 1. The CSV we just updated (data-branch/history.csv)
          # 2. The destination README (data-branch/README.md)
          
          python3 scripts/generate_dashboard.py data-branch/history.csv data-branch/README.md
          
          # Debug: Check if it looks right
          head -n 20 data-branch/README.md

      # commit and push
      - name: Commit and Push
        working-directory: data-branch
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Benchmark: ${{ env.bench_version }}"
          git push origin HEAD:benchmarks


  # --- JOB 2: DEPLOY (Web/WASM) ---
  deploy:
    needs: benchmark # <--- CRITICAL: Only runs if benchmark passes
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Setup Cache
        uses: ./.github/actions/setup-zig-cache

      # Build and push production (Target: production)
      - name: Build and Push Production Image
        uses: docker/build-push-action@v5
        with:
          context: .
          target: production
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
          #  use GitHub Actions Cache for Docker layers
          cache-from: type=gha
          cache-to: type=gha,mode=max
